### ISSUE TITLE
Améliorations

### ISSUE THREAD

**Issue by fenollp** [WebteamPS/livre-noir-fn#20]
- [x] Supprimer les `.DS_Store` du repo
  1. `find . -name .DS_Store -delete`
  2. `git rm …`
  3. Merge #19 
- [x] Supprimer la branche `master`
  - elle ne diffère pas de `gh-pages`
  - tu ne t'en sers pas
- [x] Mettre la branche `gh-pages` en défault (dans Settings)
- [x] Achètes un nom de domaine
  - [x] puis ajoute un `CNAME`
- [x] Sinon, reste avec un subtld `*.github.io` mais passe les liens en HTTPS

**Comment by WebteamPS** [comment]
Merci pour votre retour très apprécié !
